billboard_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('listings.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]


urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

listings/urls.py
from django.urls import path

from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, SearchResultsListView, \
    add_subscription, remove_subscription, CategoryDetail, add_comment_like, add_comment_dislike, update_rating_up, update_rating_down


urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('<int:pk>/edit/', PostUpdateView.as_view(), name='post_edit'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path('new/', PostCreateView.as_view(), name='post_create'),
    path("search/", SearchResultsListView.as_view(), name="search_results"),
    path('categories/', CategoryDetail.as_view(), name='test'),
    path('categories/subscribe/category/<int:pk>', add_subscription, name='subscribe_to_category'),
    path('categories/unsubscribe/category/<int:pk>', remove_subscription, name='unsubscribe_to_category'),
    path('plusratingcomment/<int:pk>/', add_comment_like, name='add_comment_like'),
    path('minusratingcomment/<int:pk>/', add_comment_dislike, name='add_comment_dislike'),
    path('pluscontent/<int:pk>/', update_rating_up, name='add_content_like'),
    path('minuscontent/<int:pk>/', update_rating_down, name='add_content_dislike'),
]

listings/models.py
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from django.db.models import Sum
from django.db import models
from django.urls import reverse


class Author(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    author_rating = models.SmallIntegerField(default=0)

    def update_rating(self):
        cont_rating = self.post_set.aggregate(contentRating=Sum('rating'))
        contRat = 0
        contRat += cont_rating.get('contentRating')

        comm_rating = self.author.comment_set.aggregate(commentRating=Sum('comment_rating'))
        commRat = 0
        commRat += comm_rating.get('commentRating')

        self.author_rating = contRat * 3 + commRat
        self.save()

    def __str__(self):
        return self.author.username


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    content = RichTextUploadingField()
    rating = models.SmallIntegerField(default=0)
    register_date = models.DateTimeField(auto_now_add=True)
    post_category = models.ManyToManyField('Category', through='PostCategory')

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return f'{str(self.content)[:125].strip()}...'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])


class Category(models.Model):
    category_name = models.CharField(max_length=100)
    category_subs = models.ManyToManyField(User, through='CategorySubs', blank=True)

    def __str__(self):
        return self.category_name


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.post.post_category.all().last()


class Comment(models.Model):
    comment_text = RichTextUploadingField()
    comment_post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_author = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_rating = models.SmallIntegerField(default=0)
    comment_date = models.DateTimeField(auto_now_add=True)

    def like(self):
        self.comment_rating += 1
        self.save()

    def dislike(self):
        self.comment_rating -= 1
        self.save()


class CategorySubs(models.Model):
    cat_sub_user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    cat_sub_category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)

listings/forms.py
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from allauth.account.forms import SignupForm
from django.contrib.auth.models import Group

from .models import Post, Comment, Author


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'post_category', ]

    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get('title')
        content = cleaned_data.get('content')

        if title == content:
            raise ValidationError(
                'Название и содержимое статьи (новости) не должны совпадать'
            )
        return cleaned_data


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_text', ]


class AuthorSignupForm(SignupForm):

    def save(self, request):
        user = super(AuthorSignupForm, self).save(request)
        author_group = Group.objects.get(name='author')
        author_group.user_set.add(user)
        Author.objects.create(author=user, author_id=user.id)
        return user

listings/views.py
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives
from django.urls import reverse_lazy, reverse
from django.contrib.sites.models import Site
from django.shortcuts import redirect
from django.db.models import Q

from .models import Post, Author, Comment, Category, CategorySubs
from .forms import CommentForm, PostForm
from billboard_project.settings import SERVER_EMAIL


class PostListView(ListView):
    model = Post
    template_name = 'listing/main.html'
    context_object_name = 'listings'
    paginate_by = 10
    ordering = 'register_date'


class PostDetailView(DetailView, FormView):
    model = Post
    template_name = 'listing/detail.html'
    context_object_name = 'one_post'
    form_class = CommentForm

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        post = self.get_object()
        return reverse("post_detail", kwargs={"pk": post.pk})

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.comment_post = self.object
        comment.comment_author = self.request.user
        comment.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['site'] = Site.objects.get_current().domain
        context['comment'] = Comment
        return context


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = "listing/new.html"
    form_class = PostForm

    def form_valid(self, form):
        post = form.save(commit=False)
        init_author = Author.objects.get(author=self.request.user)
        post.author = init_author
        return super().form_valid(form)


class PostDeleteView(LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = "listing/delete.html"
    success_url = reverse_lazy("post_list")
    permission_required = ('listings.delete_post',)

    def test_func(self):
        obj = self.get_object()
        return obj.author.author == self.request.user


class PostUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    template_name = "listing/edit.html"
    permission_required = ('listings.change_post',)

    fields = (
        "title",
        "content",
    )

    def form_valid(self, form):
        post = form.save(commit=False)
        init_author = Author.objects.get(author=self.request.user)
        post.author = init_author
        return super().form_valid(form)

    def test_func(self):
        obj = self.get_object()
        return obj.author.author == self.request.user


class SearchResultsListView(ListView):
    model = Post
    context_object_name = 'listings_list'
    template_name = 'listing/search_results.html'
    ordering = ['-title']
    paginate_by = 10
    queryset = Post.objects.all().order_by('id')

    def get_queryset(self):
        query = self.request.GET.get("q")
        return Post.objects.filter(
            Q(title__icontains=query) | Q(author__author__username__contains=query)
        )


class CategoryDetail(PermissionRequiredMixin, ListView):
    model = Category
    context_object_name = 'category_detail'
    template_name = 'listing/cat_subs.html'
    permission_required = ('listings.view_category',)

    def get_context_data(self, **kwargs):
        id = self.kwargs.get('id')
        user = self.request.user
        context = super().get_context_data(**kwargs)
        context['category_post'] = Post.objects.filter(postcategory=id)
        context['catgr'] = Category.objects.filter(id=id)
        is_subscribed = CategorySubs.objects.filter(cat_sub_category_id=id, cat_sub_user_id=user.id).exists()
        context['subscribe'] = is_subscribed
        return context


@login_required
def add_subscription(request, pk):
    user = request.user
    catgr = Category.objects.get(id=pk)
    is_subscribed = CategorySubs.objects.filter(cat_sub_user_id=user.id, cat_sub_category_id=catgr.id).exists()

    if request.method == 'POST':
        if not is_subscribed:
            CategorySubs.objects.create(cat_sub_user_id=user.id, cat_sub_category_id=catgr.id)
            catgr_repr = f'{catgr}'
            email = user.email
            msg = EmailMultiAlternatives(
                subject=f'Subscription to {catgr_repr} category',
                body=f'Вы {user} успешно подписались на категорию {catgr_repr}',
                from_email=SERVER_EMAIL,
                to=[email, ],
            )
            html_content = render_to_string(
                'listing/subscription_success.html',
                {
                    'user': user,
                    'category': catgr_repr,
                }
            )
            msg.attach_alternative(html_content, 'text/html')
            msg.send()

        elif not CategorySubs.objects.filter(cat_sub_category_id=catgr.id):
            CategorySubs.objects.create(cat_sub_user_id=user.id, cat_sub_category_id=catgr.id)
            catgr_repr = f'{catgr}'
            email = user.email
            msg = EmailMultiAlternatives(
                subject=f'Subscription to {catgr_repr} category',
                body=f'Вы {user} успешно подписались на категорию {catgr_repr}',
                from_email=SERVER_EMAIL,
                to=[email, ],
            )
            html_content = render_to_string(
                'listing/subscription_success.html',
                {
                    'user': user,
                    'category': catgr_repr,
                }
            )
            msg.attach_alternative(html_content, 'text/html')
            msg.send()

    return redirect('/')


@login_required
def remove_subscription(request, pk):
    user = request.user
    catgr = Category.objects.get(id=pk)
    if CategorySubs.objects.filter(cat_sub_user_id=user.id):
        CategorySubs.objects.filter(cat_sub_category_id=catgr.id, cat_sub_user_id=user.id).delete()
    return redirect('/')


def add_comment_like(request, pk):
    comment = Comment.objects.get(id=pk)
    comment.like()
    return redirect(request.META.get('HTTP_REFERER'))


def add_comment_dislike(request, pk):
    comment = Comment.objects.get(id=pk)
    comment.dislike()
    return redirect(request.META.get('HTTP_REFERER'))


def update_rating_up(request, pk):
    post = Post.objects.get(id=pk)
    post.like()
    return redirect(request.META.get('HTTP_REFERER'))


def update_rating_down(request, pk):
    post = Post.objects.get(id=pk)
    post.dislike()
    return redirect(request.META.get('HTTP_REFERER'))

templates/listing/cat_subs.html
{% extends 'flatpages/default.html' %}
{% load i18n %}

{% load custom_tags %}

{% block title %}{% trans "Category subscribtion" %}{% endblock title %}

{% block content %}
<html lang="rus">
<h3>{% trans "Select the category to subscribe" %}</h3>
    <hr>
{% for name in category_detail %}
<form action="{% url 'subscribe_to_category' name.id %}" method="post">{% csrf_token %}
    <h6>
        <a href="{% url 'subscribe_to_category' name.id %}">
            <button class="btn btn-outline-success">{% trans "Subscribe to" %} {{ name }}</button>
        </a>
    </h6>
</form>
{% endfor %}

<h3 style="margin-top: 50px">{% trans "Select the category to unsubscribe" %}</h3>
    <hr>
{% for name in category_detail %}
<form action="{% url 'unsubscribe_to_category' name.id %}" method="post">{% csrf_token %}
    <h6>
        <a href="{% url 'unsubscribe_to_category' name.id %}">
            <button class="btn btn-outline-danger">{% trans "Unsubscribe from" %} {{ name }}</button>
        </a>
    </h6>
</form>
{% endfor %}
{% endblock content %}
</html>

templates/listing/delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Delete</h1>
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object.title }}"?</p>
    <button class="btn btn-danger ml-2" type="submit">Confirm</button>
</form>
{% endblock content %}

templates/listing/detail.html
{% extends 'flatpages/default.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% load i18n %}

{% load crispy_forms_tags %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

{% block content %}
<div class="article-entry">
    <h2>{{ one_post.title }}</h2>
    <p>by {{ one_post.author }} | {{ one_post.register_date }}
        {% if one_post.postcategory_set.exists %}
           | {{ one_post.post_category.last }}</p>
        {% endif %}
    <p>{{ one_post.content|safe }}</p>
</div>

<hr>
<h4>Comments</h4>
{% for com in one_post.comment_set.all %}
    {% if com %}
        <p align="left"><strong>{{ com.comment_author }}</strong> &middot; {{ com.comment_text }}</p>
        <p align="left">{% trans "Rating" %}: {{ com.comment_rating }}</p>
            {% if request.user.is_authenticated %}
                <form style="margin-bottom: 10px" action="{% url 'add_comment_like' com.pk %}" method="post">
                    {% csrf_token %}
                    <button style="margin-right: 1600px" class="btn btn-outline-success">Like</button>
                </form>
                <form action="{% url 'add_comment_dislike' com.pk %}" method="post">
                    {% csrf_token %}
                    <button style="margin-right: 1600px" class="btn btn-outline-danger">Dislike</button>
                </form>
            {% endif %}
    {% endif %}
    <hr>
{% endfor %}
<hr>

{% if request.user.is_authenticated %}
    <form action="" method="post">{% csrf_token %}
        {{ form|crispy }}
        <p align="left"><button class="btn btn-outline-dark" type="submit">Save</button></p>
    </form>
{% else %}
    <h5>To leave a comment, please <a href="/accounts/login">log in</a></h5>
{% endif %}

{% if one_post.author.author == request.user %}
    <p><a href="{% url 'post_edit' one_post.pk %}">Edit</a> |
        <a href="{% url 'post_delete' one_post.pk %}">Delete</a>
    </p>
{% endif %}
<p>Back to <a href="{% url 'post_list' %}">All articles</a>.</p>
{% endblock content %}

templates/listing/edit.html
{% extends 'flatpages/default.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

{% block content %}
<h1>Edit</h1>
<form action="" method="post">{% csrf_token %}
    {{ form.media }}
    {{ form|crispy|safe }}
    <button class="btn btn-info ml-2" type="submit">Update</button>
</form>
{% endblock content %}

templates/listing/main.html
{% extends 'flatpages/default.html' %}

{% load custom_tags %}

{% block content %}
{% for post in listings %}
<div class="card">
    <div class="card-header">
        <a href="{% url 'post_detail' post.pk %}">{{ post.title }}</a>
        &middot;
        <span class="text-muted">by {{ post.author }} |
            {{ post.register_date }}
            {% if post.rating %}
           | Рейтинг {{ post.rating }}
            {% endif %}
        </span>
            <div>
                {% if request.user.is_authenticated %}
                    <form style="float: left; margin-right: 2px; margin-top: 5px" action="{% url 'add_content_like' post.pk %}">
                        {% csrf_token %}
                        <button class="btn btn-outline-success">Like</button>
                    </form>
                    <form style="float: left; margin-right: 2px; margin-top: 5px" action="{% url 'add_content_dislike' post.pk %}">
                        {% csrf_token %}
                        <button class="btn btn-outline-danger">Dislike</button>
                    </form>
                {% endif %}
            </div>
            <span style="float: right" class="text-muted">
                {% if post.postcategory_set.exists %}
                    <a href="/categories/">Категория</a>
                     {{ post.post_category.last }}</span>
                {% endif %}
    </div>
    <div class="card-body">
        <p>{{ post.content|safe }}</p>
        {% if post.author.author == request.user %}
            <a href="{% url 'post_edit' post.pk %}">Edit</a> |
            <a href="{% url 'post_delete' post.pk %}">Delete</a>
        {% endif %}
    </div>
    <div class="card-footer">
        {% for comm in post.comment_set.all %}
        <p>
            <span class="font-weight-bold">
                {{ comm.comment_author }} &middot;
            </span>
            {{ comm.comment_text|safe }} &middot;
            <span class="text-muted">{{ comm.comment_date }}</span>
        </p>
        {% endfor %}
    </div>
<br />
</div>
{% endfor %}
<div style="text-align: center">
    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}
</div>
{% endblock content %}

templates/listing/new.html
{% extends 'flatpages/default.html' %}
{% load static %}
{% load crispy_forms_filters %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

{% load crispy_forms_tags %}

{% block content %}
<h1>New post</h1>
<form action="" method="post">{% csrf_token %}
    {{ form.media }}
    {{ form|crispy }}
    <button class="btn btn-success ml-2" type="submit">Save</button>
</form>
{% endblock content %}

templates/listing/search_results.html
{% extends "flatpages/default.html" %}

{% load custom_tags %}

{% block content %}

<h1>Результаты поиска</h1>
    <hr>
{% if listings_list %}
    {% for post in listings_list %}
        <div class="card">
            <div class="card-header">
                <a href="{% url 'post_detail' post.pk %}">{{ post.title }}</a>
                &middot;
                <span class="text-muted">by {{ post.author }} |
                    {{ post.register_date }}</span>
                {% if post.postcategory_set.exists %}
                <span style="float: right" class="text-muted">Категория {{ post.post_category.last }}</span>
                {% endif %}
            </div>
            <div class="card-body">
                <p>{{ post.content|safe }}</p>
                {% if post.author.author == request.user %}
                    <a href="{% url 'post_edit' post.pk %}">Edit</a> |
                    <a href="{% url 'post_delete' post.pk %}">Delete</a>
                {% endif %}
            </div>
            <div class="card-footer">
                {% for comm in post.comment_set.all %}
                <p>
                    <span class="font-weight-bold">
                        {{ comm.comment_author }} &middot;
                    </span>
                    {{ comm.comment_text|safe }}
                </p>
                {% endfor %}
            </div>
        <br />
</div>
    {% endfor %}
{% else %}
    <div class="card">
        <div class="card-header">
            <h5>Пока ничего здесь нет...</h5>
        </div>
        <div class="card-body">
            {% if request.user.is_authenticated %}
                <p>Но вы можете это <a href="/new/">исправить:)</a></p>
            {% else %}
                <p>Но вы можете это <a href="/accounts/login/">исправить:)</a></p>
        </div>
            {% endif %}
    </div>
{% endif %}
<div style="text-align: center">
    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}
</div>
{% endblock content %}

templates/listing/subscription_success.html
<!DOCTYPE html>
{% load i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% trans "Subscription success" %}</title>
</head>
<body>
<h2>{% trans "Hello" %}, <strong>{{ user }}</strong>! {% trans "You have subscribed on the category" %} <strong>{{ category }}</strong></h2>
<h4>{% trans "Sincerely yours" %},</h4>
<h4>{% trans "BillyBoard.inc" %}</h4>
</body>
</html>

templates/listing/weekly_posts.html
<!DOCTYPE html>
{% load i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% trans "Weekly articles feed" %}</title>
</head>
<body>
<h1>{% trans "Hello" %}, {{ recipient }}! {% trans "Your fresh weekly feed on the" %} {{ category }} {% trans "is already here" %}!</h1>
{% for feed in week_feed %}
    <h3>{% trans "Title:" %} <a href="127.0.0.1/{{ feed.post.id }}/"><strong>{{ feed.post.title }}</strong></a></h3>
    <h4>{% trans "Summary" %} <strong>{{ feed.post.content|safe|truncatechars:50 }}</strong></h4>
{% endfor %}
</body>
</html>